import type { Language } from "./models";

const it = {
  nav: { home: "Home", tournaments: "Tornei", players: "Players", events: "Eventi", rules: "Regolamento", about: "Chi siamo", contact: "Contatti" },
  auth: { login: "Accedi", register: "Registrati", loginTitle: "Bentornato nel circuito", registerTitle: "Crea il tuo profilo player", email: "Email", password: "Password", username: "Username", platform: "Piattaforma", continue: "Continua", noAccount: "Non hai ancora un profilo?", hasAccount: "Hai già un profilo?", close: "Chiudi" },
  hero: { eyebrow: "L'ARENA COMPETITIVA ITALIANA", title: "Il circuito è aperto.", body: "Tornei Call of Duty in presenza, ranking nazionale e una community costruita per chi vuole competere davvero.", primary: "Scopri i tornei", secondary: "Crea il tuo profilo", next: "Prossimo evento", location: "Milano", statEvents: "eventi dal vivo", statPlayers: "player registrati", statCities: "città italiane" },
  common: { viewAll: "Vedi tutti", learnMore: "Scopri di più", date: "Data", time: "Orario", format: "Formato", platform: "Piattaforma", capacity: "Capienza", prize: "Montepremi", location: "Location", team: "Team", independent: "Free agent", points: "punti", wins: "vittorie", search: "Cerca", status: "Stato", back: "Indietro", spots: "posti", registered: "iscritti", submit: "Invia", sending: "Invio...", success: "Messaggio inviato. Ti risponderemo presto." },
  status: { open: "Iscrizioni aperte", limited: "Ultimi posti", closed: "Iscrizioni chiuse", completed: "Concluso", upcoming: "In arrivo", past: "Passato" },
  home: { tournamentsEyebrow: "NEXT UP", tournamentsTitle: "La prossima sfida ti aspetta.", tournamentsBody: "Eventi LAN costruiti attorno a regole chiare, postazioni competitive e un'esperienza all'altezza dei player.", playersEyebrow: "RANKING ICDC", playersTitle: "I player fanno il circuito.", playersBody: "Profili verificati, risultati tracciati e una classifica nazionale destinata a crescere stagione dopo stagione.", manifesto: "Competizione seria. Community aperta.", manifestoBody: "ICDC nasce per dare al competitivo italiano luoghi, regole e continuità. Dal primo match offline al main stage." },
  tournaments: { eyebrow: "CALENDARIO 2026 / 27", title: "Tornei", body: "Scopri i prossimi appuntamenti ufficiali ICDC e assicurati un posto nel bracket.", all: "Tutti", available: "Aperti", past: "Conclusi", register: "Iscriviti", details: "Dettagli torneo", remaining: "disponibili", requirements: "Come partecipare", requirementItems: ["Crea un profilo player verificato", "Completa o unisciti a un roster", "Conferma l'iscrizione e il check-in"], rules: "Regolamento", schedule: "Programma", participation: "Partecipazione", participationBody: "L'iscrizione è personale. Il team captain completa il roster e riceve via email le istruzioni di pagamento e check-in.", registrationTitle: "Pronto a entrare nel bracket?", registrationBody: "Accedi o crea il tuo profilo per iniziare l'iscrizione." },
  players: { eyebrow: "COMMUNITY COMPETITIVA", title: "Players", body: "Scopri chi sta costruendo la scena competitiva ICDC, una mappa alla volta.", placeholder: "Cerca username, team o paese", ranking: "Ranking", player: "Player", role: "Ruolo", profile: "Profilo", empty: "Nessun player corrisponde alla ricerca.", joinTitle: "Il prossimo nome può essere il tuo.", joinBody: "Crea un profilo, partecipa ai tornei e costruisci il tuo storico competitivo." },
  events: { eyebrow: "DAL VIVO", title: "Eventi", body: "Le partite contano di più quando il pubblico è a un metro dal palco.", upcoming: "Prossimi eventi", past: "Eventi passati", info: "Informazioni evento", gallery: "Galleria in arrivo" },
  rules: { eyebrow: "FAIR PLAY, SEMPRE", title: "Regolamento", body: "Standard chiari proteggono player, organizzatori e qualità della competizione.", general: "Regolamento generale ASD", generalBody: "Codice di condotta, requisiti di partecipazione, gestione dei dati e procedure disciplinari.", competitive: "Regole competitive", competitiveBody: "Impostazioni di gioco, periferiche consentite, map pool e gestione delle contestazioni.", download: "Scarica PDF", updated: "Aggiornato il 15 settembre 2026", principles: ["Rispetto verso avversari, staff e pubblico", "Integrità competitiva e zero tolleranza per il cheating", "Puntualità a check-in e match call", "Tutela dei minori e trattamento responsabile dei dati"], specific: "Regolamenti torneo" },
  about: { eyebrow: "L'ASSOCIAZIONE", title: "Più di un bracket.", body: "Italian CoD Circuit è un'Associazione Sportiva Dilettantistica nata per rendere il competitive gaming italiano più organizzato, accessibile e riconoscibile.", missionTitle: "La nostra missione", missionBody: "Creiamo un circuito LAN continuativo dove player emergenti e veterani possano incontrarsi, competere e crescere attraverso standard professionali.", valuesTitle: "Cosa difendiamo", values: [{ title: "Integrità", body: "Regole trasparenti e arbitraggio indipendente." }, { title: "Accesso", body: "Percorsi competitivi aperti a nuovi talenti." }, { title: "Community", body: "Eventi che fanno incontrare persone, non solo account." }], legal: "ASD registrata in Italia · Codice fiscale 97900000001" },
  contact: { eyebrow: "PARLIAMONE", title: "Contatti", body: "Player, team, venue o partner: raccontaci cosa vuoi portare nel circuito.", email: "Email", discord: "Discord", social: "Social", formTitle: "Scrivi al team ICDC", name: "Nome", emailLabel: "Email", topic: "Argomento", message: "Messaggio", topics: ["Partecipazione torneo", "Team e player", "Partnership", "Media", "Altro"], privacy: "Inviando il modulo accetti il trattamento dei dati per rispondere alla richiesta." },
  footer: { description: "Il circuito italiano dedicato al competitive Call of Duty dal vivo.", explore: "Esplora", community: "Community", rights: "Italian CoD Circuit ASD. Tutti i diritti riservati.", disclaimer: "Non affiliato o sponsorizzato da Activision Publishing, Inc." },
};

const en = {
  nav: { home: "Home", tournaments: "Tournaments", players: "Players", events: "Events", rules: "Rules", about: "About", contact: "Contact" },
  auth: { login: "Login", register: "Register", loginTitle: "Welcome back to the circuit", registerTitle: "Create your player profile", email: "Email", password: "Password", username: "Username", platform: "Platform", continue: "Continue", noAccount: "Don't have a profile yet?", hasAccount: "Already have a profile?", close: "Close" },
  hero: { eyebrow: "ITALY'S COMPETITIVE ARENA", title: "The circuit is live.", body: "In-person Call of Duty tournaments, national rankings and a community built for those who are serious about competing.", primary: "Discover tournaments", secondary: "Create your profile", next: "Next event", location: "Milan", statEvents: "live events", statPlayers: "registered players", statCities: "Italian cities" },
  common: { viewAll: "View all", learnMore: "Learn more", date: "Date", time: "Time", format: "Format", platform: "Platform", capacity: "Capacity", prize: "Prize pool", location: "Location", team: "Team", independent: "Free agent", points: "points", wins: "wins", search: "Search", status: "Status", back: "Back", spots: "spots", registered: "registered", submit: "Send", sending: "Sending...", success: "Message sent. We'll get back to you soon." },
  status: { open: "Registration open", limited: "Last spots", closed: "Registration closed", completed: "Completed", upcoming: "Upcoming", past: "Past" },
  home: { tournamentsEyebrow: "NEXT UP", tournamentsTitle: "Your next challenge awaits.", tournamentsBody: "LAN events built around clear rules, competitive stations and an experience worthy of the players.", playersEyebrow: "ICDC RANKING", playersTitle: "Players make the circuit.", playersBody: "Verified profiles, tracked results and a national ranking designed to grow season after season.", manifesto: "Serious competition. Open community.", manifestoBody: "ICDC gives Italian competitive gaming the venues, rules and continuity it deserves. From the first offline match to the main stage." },
  tournaments: { eyebrow: "2026 / 27 CALENDAR", title: "Tournaments", body: "Explore upcoming official ICDC events and secure your place in the bracket.", all: "All", available: "Open", past: "Completed", register: "Register", details: "Tournament details", remaining: "remaining", requirements: "How to participate", requirementItems: ["Create a verified player profile", "Complete or join a roster", "Confirm registration and check-in"], rules: "Rules", schedule: "Schedule", participation: "Participation", participationBody: "Registration is personal. The team captain completes the roster and receives payment and check-in instructions by email.", registrationTitle: "Ready to enter the bracket?", registrationBody: "Log in or create your profile to begin registration." },
  players: { eyebrow: "COMPETITIVE COMMUNITY", title: "Players", body: "Meet the people building the ICDC competitive scene, one map at a time.", placeholder: "Search username, team or country", ranking: "Ranking", player: "Player", role: "Role", profile: "Profile", empty: "No players match your search.", joinTitle: "The next name could be yours.", joinBody: "Create a profile, enter tournaments and build your competitive history." },
  events: { eyebrow: "LIVE", title: "Events", body: "Matches matter more when the crowd is one metre from the stage.", upcoming: "Upcoming events", past: "Past events", info: "Event information", gallery: "Gallery coming soon" },
  rules: { eyebrow: "FAIR PLAY, ALWAYS", title: "Rules", body: "Clear standards protect players, organisers and the quality of competition.", general: "General ASD rules", generalBody: "Code of conduct, participation requirements, data handling and disciplinary procedures.", competitive: "Competitive rules", competitiveBody: "Game settings, approved peripherals, map pool and dispute handling.", download: "Download PDF", updated: "Updated 15 September 2026", principles: ["Respect for opponents, staff and spectators", "Competitive integrity and zero tolerance for cheating", "Punctuality for check-in and match calls", "Protection of minors and responsible data handling"], specific: "Tournament rules" },
  about: { eyebrow: "THE ASSOCIATION", title: "More than a bracket.", body: "Italian CoD Circuit is an Italian amateur sports association created to make competitive gaming more organised, accessible and recognisable.", missionTitle: "Our mission", missionBody: "We create a continuous LAN circuit where emerging players and veterans can meet, compete and grow through professional standards.", valuesTitle: "What we stand for", values: [{ title: "Integrity", body: "Transparent rules and independent officiating." }, { title: "Access", body: "Competitive paths open to new talent." }, { title: "Community", body: "Events that bring people together, not just accounts." }], legal: "ASD registered in Italy · Tax code 97900000001" },
  contact: { eyebrow: "LET'S TALK", title: "Contact", body: "Player, team, venue or partner: tell us what you want to bring to the circuit.", email: "Email", discord: "Discord", social: "Social", formTitle: "Write to team ICDC", name: "Name", emailLabel: "Email", topic: "Topic", message: "Message", topics: ["Tournament participation", "Teams and players", "Partnership", "Media", "Other"], privacy: "By submitting the form, you agree to data processing for the purpose of responding to your request." },
  footer: { description: "Italy's live competitive Call of Duty circuit.", explore: "Explore", community: "Community", rights: "Italian CoD Circuit ASD. All rights reserved.", disclaimer: "Not affiliated with or sponsored by Activision Publishing, Inc." },
};

export const content: Record<Language, typeof it> = { it, en };
export type SiteContent = typeof it;