import type { CircuitEvent, Player, Tournament } from "./models";

export const tournaments: Tournament[] = [
  {
    id: "milano-open-2026",
    name: "Milano Open LAN",
    game: "Call of Duty: Black Ops 7",
    date: "2026-11-14",
    time: "09:30",
    format: "4v4 Hardpoint / S&D / Control",
    platform: "Cross-play",
    capacity: 16,
    registered: 11,
    prizePool: "€ 2.500",
    status: "open",
    location: "Milano Esports Arena",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1600&q=85",
    description: {
      it: "Il primo major LAN della stagione ICDC. Due giorni di competizione, postazioni professionali e finali sul main stage.",
      en: "The first ICDC LAN major of the season. Two days of competition, professional stations and main-stage finals.",
    },
    rules: [
      { it: "Roster di 4 titolari e massimo 1 riserva.", en: "Roster of 4 starters and up to 1 substitute." },
      { it: "Controller ammessi; macro e rapid fire vietati.", en: "Controllers allowed; macros and rapid fire are prohibited." },
      { it: "Check-in obbligatorio entro le 09:00.", en: "Mandatory check-in by 09:00." },
    ],
    schedule: [
      { time: "08:30", label: { it: "Apertura check-in", en: "Check-in opens" } },
      { time: "09:30", label: { it: "Fase a gironi", en: "Group stage" } },
      { time: "15:30", label: { it: "Playoff", en: "Playoffs" } },
      { time: "19:30", label: { it: "Grand Final", en: "Grand Final" } },
    ],
  },
  {
    id: "roma-challenger-2027",
    name: "Roma Challenger",
    game: "Call of Duty: Black Ops 7",
    date: "2027-01-23",
    time: "10:00",
    format: "4v4 CDL Ruleset",
    platform: "PlayStation 5",
    capacity: 12,
    registered: 10,
    prizePool: "€ 1.500",
    status: "limited",
    location: "Level Up Roma",
    image: "https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=1600&q=85",
    description: {
      it: "Un challenger compatto ad alta intensità per i team che puntano alla classifica nazionale.",
      en: "A compact, high-intensity challenger for teams targeting the national ranking.",
    },
    rules: [
      { it: "Regolamento competitivo CDL vigente.", en: "Current CDL competitive rules apply." },
      { it: "Tutti i player devono avere un profilo ICDC verificato.", en: "All players must have a verified ICDC profile." },
      { it: "Doppia eliminazione dopo la fase svizzera.", en: "Double elimination after the Swiss stage." },
    ],
    schedule: [
      { time: "09:00", label: { it: "Accredito team", en: "Team accreditation" } },
      { time: "10:00", label: { it: "Swiss stage", en: "Swiss stage" } },
      { time: "16:00", label: { it: "Top 8", en: "Top 8" } },
      { time: "20:00", label: { it: "Premiazione", en: "Awards" } },
    ],
  },
  {
    id: "bologna-rookie-cup",
    name: "Bologna Rookie Cup",
    game: "Call of Duty: Black Ops 7",
    date: "2027-03-06",
    time: "11:00",
    format: "2v2 Gunfight",
    platform: "Cross-play",
    capacity: 32,
    registered: 18,
    prizePool: "Hardware + € 600",
    status: "open",
    location: "Play District Bologna",
    image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1600&q=85",
    description: {
      it: "Il torneo accessibile pensato per nuovi competitor e duo emergenti, con coaching corner e open qualifier.",
      en: "An accessible tournament for new competitors and emerging duos, with a coaching corner and open qualifier.",
    },
    rules: [
      { it: "Aperto a duo senza ranking nazionale.", en: "Open to duos without a national ranking." },
      { it: "Loadout predefiniti per ogni round.", en: "Preset loadouts for every round." },
      { it: "Gironi più bracket a eliminazione diretta.", en: "Groups followed by a single-elimination bracket." },
    ],
    schedule: [
      { time: "10:00", label: { it: "Warm-up e check-in", en: "Warm-up and check-in" } },
      { time: "11:00", label: { it: "Gironi", en: "Groups" } },
      { time: "15:00", label: { it: "Bracket finale", en: "Final bracket" } },
      { time: "18:30", label: { it: "Finale", en: "Final" } },
    ],
  },
  {
    id: "napoli-finals-2026",
    name: "ICDC Finals Napoli",
    game: "Call of Duty: Black Ops 6",
    date: "2026-06-20",
    time: "10:00",
    format: "4v4 Championship",
    platform: "Cross-play",
    capacity: 8,
    registered: 8,
    prizePool: "€ 5.000",
    status: "completed",
    location: "Mostra d'Oltremare, Napoli",
    image: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?auto=format&fit=crop&w=1600&q=85",
    description: {
      it: "La finale della stagione 2025/26 che ha riunito gli otto migliori team del ranking nazionale.",
      en: "The 2025/26 season final, bringing together the top eight teams in the national ranking.",
    },
    rules: [{ it: "Evento concluso.", en: "Event completed." }],
    schedule: [{ time: "20:30", label: { it: "Vincitore: Nova Unit", en: "Winner: Nova Unit" } }],
  },
];

export const players: Player[] = [
  { id: "p1", username: "R3VOLT", avatar: "https://i.pravatar.cc/300?img=12", country: "Italia", countryCode: "IT", platform: "PS5", role: "Slayer", team: "Nova Unit", wins: 38, kd: 1.28, points: 2840 },
  { id: "p2", username: "KIRO", avatar: "https://i.pravatar.cc/300?img=47", country: "Italia", countryCode: "IT", platform: "PC", role: "Flex", team: "Aeterna", wins: 31, kd: 1.19, points: 2610 },
  { id: "p3", username: "NEX", avatar: "https://i.pravatar.cc/300?img=33", country: "Svizzera", countryCode: "CH", platform: "PS5", role: "Main AR", wins: 29, kd: 1.24, points: 2495 },
  { id: "p4", username: "VANTA", avatar: "https://i.pravatar.cc/300?img=25", country: "Italia", countryCode: "IT", platform: "Xbox", role: "Entry", wins: 27, kd: 1.16, points: 2350 },
  { id: "p5", username: "SYNAPSE", avatar: "https://i.pravatar.cc/300?img=5", country: "Francia", countryCode: "FR", platform: "PC", role: "Objective", team: "Lynx EU", wins: 24, kd: 1.09, points: 2210 },
  { id: "p6", username: "MAVE", avatar: "https://i.pravatar.cc/300?img=44", country: "Italia", countryCode: "IT", platform: "PS5", role: "Flex", wins: 21, kd: 1.13, points: 2090 },
];

export const events: CircuitEvent[] = [
  {
    id: "milano-open",
    name: { it: "Milano Open LAN", en: "Milan Open LAN" },
    date: "2026-11-14",
    location: "Milano Esports Arena",
    status: "upcoming",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1400&q=85",
    description: { it: "Due giorni di torneo, creator showmatch e area community.", en: "Two days of tournaments, creator showmatches and a community area." },
  },
  {
    id: "bologna-community",
    name: { it: "Community Night Bologna", en: "Bologna Community Night" },
    date: "2026-12-12",
    location: "Play District Bologna",
    status: "upcoming",
    image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=1400&q=85",
    description: { it: "Serata open play con mini tornei e sessioni meet the team.", en: "Open-play evening with mini tournaments and meet-the-team sessions." },
  },
  {
    id: "napoli-finals",
    name: { it: "Finals Napoli 2026", en: "Naples Finals 2026" },
    date: "2026-06-20",
    location: "Mostra d'Oltremare, Napoli",
    status: "past",
    image: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?auto=format&fit=crop&w=1400&q=85",
    description: { it: "Ottocento presenze e una finale decisa all'ultima mappa.", en: "Eight hundred attendees and a final decided on the last map." },
  },
];